name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.JS  
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - name: Build Website
        run: npm run build
      - name: Deploy Website
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_HOST }}
          source: dist/
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          remote_path: /var/www/html/
          args: --delete -avzr
